kind: pipeline
type: kubernetes
name: default

steps:
- name: docs
  image: squidfunk/mkdocs-material
  environment:
    GH_TOKEN:
      from_secret: gh_token
  commands:
  - pip install mkdocs-include-dir-to-nav
  - git remote add gh-token "https://$${GH_TOKEN}@github.com/lib42/heqet.git"
  - git fetch gh-token && git fetch gh-token gh-deploy:gh-deploy
  - cp README.md docs/index.md
  - git clone --depth=1 https://github.com/lib42/helm-heqet /tmp/helm
  - cp /tmp/helm/README.md docs/helm-plugin.md
  - mkdocs gh-deploy --clean --remote-name gh-token

- name: build-image
  image: plugins/kaniko
  environment:
    # Workaround for Kanikos container detection
    container: docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: lib42/heqet-cli
    dockerfile: Containerfile
    tags:
      - v3
      - latest
